services:
    traefik:
        image: traefik:2.11
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        networks:
            - traefik-public
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    app:
        image: ${REGISTRY}/app:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        environment:
            APP_ENV: prod
            DB_HOST: app-mysql
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/app_db_password
            DB_NAME: app
        secrets:
            - app_db_password
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.app.rule=Host(`localhost`)
            - traefik.http.routers.app.entryPoints=http
            - traefik.http.services.app.loadBalancer.server.port=80

    app-php-cli:
        image: ${REGISTRY}/app-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            DB_HOST: app-mysql
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/app_db_password
            DB_NAME: app
        secrets:
            - app_db_password

    app-mysql:
        image: mariadb:11
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/app_db_root_password
            MYSQL_USER: app
            MYSQL_PASSWORD_FILE: /run/secrets/app_db_password
            MYSQL_DATABASE: app
        secrets:
            - app_db_root_password
            - app_db_password
        ports:
            - "3306:3306"

    benchmark:
        image: ${REGISTRY}/benchmark:${IMAGE_TAG}
        network_mode: service:traefik

secrets:
    app_db_root_password:
        file: ./app/docker/development/secrets/app_db_root_password
    app_db_password:
        file: ./app/docker/development/secrets/app_db_password

networks:
    traefik-public:
        name: traefik-public
